name: "pytest-plugin-environment"
description: "This action sets up an environment for testing and building pytest plugins"


inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: "3.10"

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: 2.1.2

  just-version:
    description: 'Just version to use'
    required: true
    default: 1.16.0

runs:

  using: "composite"
  steps:

    - name: Setup Poetry (${{ inputs.poetry-version }})
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Setup Python (${{ inputs.python-version}})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup just (${{ inputs.just-version }})
      uses: extractions/setup-just@v1
      with:
        just-version: ${{ inputs.just-version }} 

