name: "pytest-plugin-environment"
description: "This action sets up an environment for testing and building pytest plugins"


inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: 3.9

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: 1.7.1

  just-version:
    description: 'Just version to use'
    required: true
    default: 1.16.0

runs:

  using: "composite"
  steps:

    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@0.13.0
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}

    - name: Setup just (${{ inputs.just-version }})
      uses: extractions/setup-just@v1
      with:
        just-version: ${{ inputs.just-version }} 

