[tool.poetry]
name = "pytest-exasol-slc"
version = "0.3.1"
description = ""
authors = ["Mikhail Beck <mikhail.beck@exasol.com>"]
readme = "README.md"
packages = [{include = "exasol"}]

[tool.poetry.dependencies]
python = ">=3.10,<4"
pytest = ">=7,<9"
pytest-exasol-backend = ">=0.3.1, <1.0.0"
pytest-exasol-extension = ">=0.2.1, <1.0.0"
exasol-python-extension-common = ">=0.8.0, <1.0.0"

[tool.poetry.plugins.pytest11]
slc = "exasol.pytest_slc"

[tool.poetry.group.dev.dependencies]
exasol-toolbox = ">=0.15.0,<1"
exasol-bucketfs = ">=0.13.0,<1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
relative_files = true
source = [
    "exasol",
]

[tool.coverage.report]
fail_under = 15


[tool.black]
line-length = 88
verbose = false
include = "\\.pyi?$"


[tool.isort]
profile = "black"
force_grid_wrap = 2


[tool.pylint.master]
fail-under = 8.1
output-format = "colorized,json:.lint.json,text:.lint.txt"

[tool.pylint.format]
max-line-length = 88
max-module-lines = 800


[[tool.mypy.overrides]]
module = [
    "test.unit.*",
    "test.integration.*",
    "exasol.toolbox.*",
    "pyexasol.*",
]
ignore_errors = true
ignore_missing_imports = true

