name: Check Release Tag

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:

  check-tag-version-job:
    name: Check Tag Version
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Check Tag Version
        working-directory: ${{ inputs.working-directory }}
        # make sure the pushed/created tag matched the project version
        run: "[[ `poetry version --short` == ${{ inputs.version }} ]]"
