name: Continues Integration (Master)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
  # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:

  show-commit-message-1:
    name: show commit message 1
    runs-on: ubuntu-20.04
    run: echo ${{ github.event.head_commit.message }}

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      commit-message: ${{ github.event.head_commit.message }}
