name: Continuous Integration (Main)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
  # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    permissions:
      contents: read
    with:
      slow-tests: true