name: Continuous Integration (Main)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
  # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:

  CI:
    strategy:
      matrix:
        working-directory :
          - pytest-backend
          - pytest-extension
          - pytest-itde
          - pytest-saas
          - pytest-slc
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      slow-tests: true
      working-directory: ${{ matrix.working-directory }}