name: Continuous Integration (PR)

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    permissions:
      contents: read
    with:
      slow-tests: true