name: Continues Integration (PR)

on:
  pull_request:

jobs:

  examine-commit-message-ci-pr:
    name: show commit message ci-pr
    runs-on: ubuntu-20.04

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Examine Commit Message in ci-pr
        run: |
          export A=5
          git log -1 --pretty=format:"%b"
          if ! (git log -1 --pretty=format:"%b" | grep "\[run-slow-tests\]"); then
             export RUN_SLOW_TESTS='-m "not slow"'
          fi

      - name: Verify setting of env var in ci-pr
        run: |
          echo "A = $A"
          echo "RUN_SLOW_TESTS = $RUN_SLOW_TESTS"

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      commit-message: ${{ github.event.head_commit.message }}
