name: Continues Integration (PR)

on:
  pull_request:

jobs:

  examine-commit-message-ci-pr:
    name: show commit message ci-pr
    runs-on: ubuntu-20.04

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: examine
        name: Examine Commit Message in ci-pr
        run: |
          echo A=5 >> "$GITHUB_OUTPUT"
          if ! (git log -2 --format="%b" | grep "\[run-slow-tests\]"); then
             echo 'RUN_SLOW_TESTS='-m "not slow"' >> "$GITHUB_OUTPUT"
          fi

      - name: Verify setting of env var in ci-pr
        run: |
          echo "OUTPUT 1 = ${{ steps.examine.outputs.A }}"
          echo "OUTPUT 2 = ${{ steps.examine.outputs.RUN_SLOW_TESTS }}"

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
