name: Continues Integration (PR)

on:
  pull_request:

jobs:

  examine-commit-message-ci-pr:
    name: show commit message ci-pr
    runs-on: ubuntu-20.04

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Examine Commit Message in ci-pr
        run: |
          echo 5 >> "$GITHUB_OUTPUT"
          git status
          git log -1 --pretty=format:"%b"
          if ! (git log -1 --pretty=format:"%b" | grep "\[run-slow-tests\]"); then
             export RUN_SLOW_TESTS='-m "not slow"' >> "$GITHUB_OUTPUT"
          fi

      - name: Verify setting of env var in ci-pr
        run: |
          echo "GITHUB_OUTPUT 1 = ${{ neegs.examine-commit-message-ci-pr.outputs.output1}}
          echo "GITHUB_OUTPUT 2 = ${{ neegs.examine-commit-message-ci-pr.outputs.output2}}

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      commit-message: ${{ github.event.head_commit.message }}
