name: Continues Integration (PR)

on:
  pull_request:

jobs:

  show-commit-message-ci-pr:
    name: show commit message ci-pr
    runs-on: ubuntu-20.04

    steps:
     - name: Show CM 1
       run: echo ${{ github.event.pull_request.head_commit.message }}

  CI:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      commit-message: ${{ github.event.head_commit.message }}
