name: Continuous Integration (PR)

on:
  pull_request:

jobs:

  CI:
    strategy:
      matrix:
        working-directory :
          - pytest-backend
          - pytest-extension
          - pytest-itde
          - pytest-saas
          - pytest-slc
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      slow-tests: true
      working-directory: ${{ matrix.working-directory }}
