name: Build Matrix (Python)

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    outputs:
      matrix:
        description: "Generates the python version build matrix"
        value: ${{ jobs.python_versions.outputs.matrix }}

jobs:
  python_versions:

    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/python-environment
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Generate matrix
        run: poetry run -- nox -s matrix:python

      - id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:python)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
